

server:
  port: 8000
spring:
  profiles: tes #生产环境

---
server:
  port: 8001
spring:
  profiles: dev #生产环境

---

mybatis:
  #  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.lisc.springcloud.entity         # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

   #以下采用     hikari 方式
spring:
  application:
    name: microservicecloud-config-dept-client
  profiles:
    active: dev

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource               # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver              # mysql驱动包
    #    driver-class-name: corg.mariadb.jdbc.Driver                # mairadb驱动包
    url: jdbc:mysql://localhost:3307/springcloud?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true&autoReconnectForPools=true            # 数据库名称
    #    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true&autoReconnectForPools=true            # 数据库名称
    username: root
    password: mysql
    druid:
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位毫秒
      time-between-eviction-runs-millis: 60000

#熔断器DashBoard：actuator在springboot2.0调整后开关 web端点的配置，”**“代表开启所有
# hystrix 2.0以后 stream 呈现有两种方式，一、创建class 设置 /hystrix.stream ,二、设置yml配置熔断器
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream



eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka  # 单机模式
  instance:
    instance-id: microservicecloud-dept8001
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: lisc-microservicecloud
  company.name: www.lisc.com
  build.artifactId: @project.artifactId@
  build.version: @project.version@
